### ISSUE TITLE
which version of keras and python do you use?

### ISSUE THREAD

**Issue by jacklone** [movchan74/street_to_shop_experiments#2]
I have tried to load the keras model use python2.7 and python3.6, but received an error like this:
```
  File "/opt/miniconda3/lib/python3.6/site-packages/keras/layers/core.py", line 663, in call
    return self.function(inputs, **arguments)
  File "<ipython-input-8-be15121d8712>", line 7, in <lambda>
SystemError: unknown opcode
```
Is this error caused by the Lamda function? Could you please show me the version of python, keras and tensorflow in this project? thanks a lot!

**Comment by movchan74** [comment]
It definitely works with python 3.4, keras 2.0.1, tensorflow 1.0.1.
```
from keras.models import load_model
model = load_model('triplet_semihard_final.keras')
```

**Comment by jacklone** [comment]
yes, it's ok! thank you again!
